
[general]
	#The material blacklist of this module.
	materialBlacklist = ["osmium", "utherium", "regalium", "starmetal"]
	#The materials to force generate passive forms for this module.
	passiveMaterialWhitelist = []

