
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have compressor to storage block recipes added.
	toStorageBlockMaterialBlacklist = []

