
[general]
	#The material blacklist of this module.
	materialBlacklist = ["utherium", "starmetal", "regalium", "osmium"]
	#The materials to force generate passive forms for this module.
	passiveMaterialWhitelist = []

