[[entities]]
  entity = "minecraft:creeper"
  minTier = 0
  maxTier = 4
  presetAffixes = []
  affixList = ["knocking", "wounding", "paralyzing", "molten"]
  affixPermission = "BLACKLIST"

[[entities]]
  entity = "undergarden:forgotten_guardian"
  minTier = 0
  maxTier = 1
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "minecraft:piglin_brute"
  minTier = 0
  maxTier = 1
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "minecraft:ender_dragon"
  minTier = 0
  maxTier = 0
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"

[[entities]]
  entity = "quark:forgotten"
  minTier = 0
  maxTier = 2
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "minecraft:wither"
  minTier = 0
  maxTier = 0
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "alexsmobs:void_worm"
  minTier = 0
  maxTier = 0
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "alexsmobs:warped_mosco"
  minTier = 0
  maxTier = 0
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "botania:doppleganger"
  minTier = 0
  maxTier = 0
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
  [[entities]]
  entity = "wildbackport:warden"
  minTier = 0
  maxTier = 0
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "minecraft:slime"
  minTier = 0
  maxTier = 0
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "minecraft:magma_cube"
  minTier = 0
  maxTier = 0
  presetAffixes = []
  affixList = ["lively", "adaptable", "shielding"]
  affixPermission = "BLACKLIST"