
#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = 16777215
	chance = 1.0
	growthFactor = 0
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = 0x9F6F2F
	chance = 0.1
	growthFactor = 1
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = 0xFAAF18
	chance = 0.2
	growthFactor = 2
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = 0xD800FF
	chance = 0.2
	growthFactor = 3
	effects = []
	presetAffixes = []
