
#List of diet effects
[[effects]]

	[[effects.attributes]]
		name = "minecraft:generic.max_health"
		operation = "add"
		amount = 2.0

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "all"
		above = 0.6
		below = 1.0

[[effects]]

	[[effects.attributes]]
		name = "minecraft:generic.max_health"
		operation = "add"
		amount = 2.0

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "every"
		above = 0.8
		below = 1.0

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:mining_fatigue"
		power = 2

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "any"
		above = 0.0
		below = 0.10

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:slowness"
		power = 2

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "any"
		above = 0.0
		below = 0.20

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:weakness"
		power = 2

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "any"
		above = 0.0
		below = 0.15

