
#List of diet effects
[[effects]]

	[[effects.attributes]]
		name = "minecraft:generic.max_health"
		operation = "add"
		amount = 1.0

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "every"
		above = 0.2
		below = 1.0

[[effects]]

	[[effects.attributes]]
		name = "minecraft:generic.max_health"
		operation = "add"
		amount = 1.0

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "every"
		above = 0.4
		below = 1.0

[[effects]]

	[[effects.attributes]]
		name = "minecraft:generic.max_health"
		operation = "add"
		amount = 1.0

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "every"
		above = 0.6
		below = 1.0

[[effects]]

	[[effects.attributes]]
		name = "minecraft:generic.max_health"
		operation = "add"
		amount = 1.0

	[[effects.conditions]]
		groups = ["proteins", "fruits", "vegetables", "grains", "sugars"]
		match = "every"
		above = 0.8
		below = 1.0