
[item_pipe]

	[item_pipe.speed]
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		no_upgrade = 10
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		basic = 8
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		improved = 6
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		advanced = 4
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		ultimate = 2

	[item_pipe.amount]
		#The amount of items transferred
		#Range: > 1
		no_upgrade = 1
		#The amount of items transferred
		#Range: > 1
		basic = 8
		#The amount of items transferred
		#Range: > 1
		improved = 16
		#The amount of items transferred
		#Range: > 1
		advanced = 32
		#The amount of items transferred
		#Range: > 1
		ultimate = 64

[fluid_pipe]

	[fluid_pipe.amount]
		#The amount of mB transferred each tick
		#Range: > 1
		no_upgrade = 50
		#The amount of mB transferred each tick
		#Range: > 1
		basic = 100
		#The amount of mB transferred each tick
		#Range: > 1
		improved = 500
		#The amount of mB transferred each tick
		#Range: > 1
		advanced = 1000
		#The amount of mB transferred each tick
		#Range: > 1
		ultimate = 8000

[energy_pipe]

	[energy_pipe.amount]
		#The amount of FE transferred each tick
		#Range: > 1
		no_upgrade = 256
		#The amount of FE transferred each tick
		#Range: > 1
		basic = 512
		#The amount of FE transferred each tick
		#Range: > 1
		improved = 1024
		#The amount of FE transferred each tick
		#Range: > 1
		advanced = 2048
		#The amount of FE transferred each tick
		#Range: > 1
		ultimate = 4096

[gas_pipe]

	[gas_pipe.amount]
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		no_upgrade = 200
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		basic = 400
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		improved = 2000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		advanced = 8000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		ultimate = 40000

