
# Let's Configure Delightful
[Knives]
	black_opal_knife = true
	bone_knife = true
	brass_knife = true
	bronze_knife = true
	constantan_knife = true
	copper_knife = true
	electrum_knife = true
	enderite_knife = true
	invar_knife = true
	lapis_lazuli_knife = true
	large_amethyst_knife = true
	lead_knife = true
	netherite_opal_knife = true
	nickel_knife = true
	obsidian_infused_enderite_knife = true
	osmium_knife = true
	refined_glowstone_knife = true
	refined_obsidian_knife = true
	silver_knife = true
	steel_knife = true
	tin_knife = true

[Cabinets]
	basalt_cabinet = true
	quartz_cabinet = true

[Other]
	azalea_tea = true
	cheeseburger = true
	chunk_nugget = true
	chunkwich = true
	cooked_marshmallow_stick = true
	crab_rangoon = true
	deluxe_cheeseburger = true
	ender_nectar = true
	green_tea_leaf = true
	honey_glazed_walnut = true
	jelly_bottle = true
	marshmallow_stick = true
	nut_butter_and_jelly_sandwich = true
	nut_butter_bottle = true
	prickly_pear_juice = true
	smore = true

