
# Let's Configure Delightful
[Knives]
	black_opal_knife = false
	bone_knife = false
	brass_knife = false
	bronze_knife = false
	constantan_knife = false
	copper_knife = false
	electrum_knife = false
	enderite_knife = false
	invar_knife = false
	lapis_lazuli_knife = false
	large_amethyst_knife = false
	lead_knife = false
	netherite_opal_knife = false
	nickel_knife = false
	obsidian_infused_enderite_knife = false
	osmium_knife = false
	refined_glowstone_knife = false
	refined_obsidian_knife = false
	silver_knife = false
	steel_knife = false
	tin_knife = false
	amethyst_knife = false
	deorum_knife = false
	draco_arcanus_knife = false
	emerald_knife = false
	fiery_knife = false
	ironwood_knife = false
	knightmetal_knife = false
	living_knife = false
	reinforced_deorum_knife = false
	steeleaf_knife = false

[Cabinets]
	basalt_cabinet = true
	quartz_cabinet = true

["Foods and Other Items"]
	animal_fat = true
	animal_oil_bottle = true
	azalea_tea = true
	berry_matcha_latte = true
	cheeseburger = true
	chunk_nugget = true
	chunkwich = true
	cooked_marshmallow_stick = true
	crab_rangoon = true
	deluxe_cheeseburger = true
	ender_nectar = true
	green_tea_leaf = true
	honey_glazed_walnut = true
	jelly_bottle = true
	marshmallow_stick = true
	matcha = true
	matcha_latte = true
	nut_butter_and_jelly_sandwich = true
	nut_butter_bottle = true
	prickly_pear_juice = true
	smore = true
	cactus_flesh = true
	cactus_steak = true
	chopped_clover = true
	field_salad = true
	glow_jelly_bottle = true
	lavender_tea = true
	mini_melon = true
	rock_candy = true
	salmonberries = true
	salmonberry_sack = true
	#Allow cooking milk from nuts
	nut_milk = false
	#Allow cooking honey from honey and clovers
	clover_honey = true
	acorn = false
	acorn_sack = false
	cooked_goat = true
	cooked_venison_chops = true
	raw_goat = true
	salmonberry_pips = true
	venison_chops = true

[Generation]
	#Chance of generating clusters. Smaller value = more frequent.
	#Range: > 0
	chance_wild_salmonberries = 30
	#Chance of generating clusters. Smaller value = more frequent.
	#Range: > 0
	chance_mini_melon = 30

