
[general]
	#Overrides are dependent on potion effects
	"Potion Active" = true
	#Creative Mode Always Removes Fog
	"Creative Overrides" = true
	#Disable the fire overlay when you're burning
	"Disable Fire Overlay" = false
	#Offset the fire overlay, negative values means down and positive is up.
	#Range: -1.0 ~ 1.0
	"Fire Overlay Offset" = -0.25
	#Disable the water overlay when you're in water
	"Disable Water Overlay" = false

[overworld]
	#Disable Overworld Fog?
	"Disable Overworld Fog" = false
	#Overworld Fog Starting Distance
	#Range: 0.1 ~ 1.0
	"Overworld Fog Starting Distance" = 0.65
	#Readds the void fog that was removed in 1.8
	"Enable Void Fog" = false
	#This is so you can adjust the starting distance of the fog
	#Range: 0.001 ~ 10.0
	"Void Fog Starting Distance" = 0.02
	#At what Y-level should the fog active on
	#Range: -64 ~ 319
	"Y-Level Activation" = 0
	#Readds the void particles that was removed in 1.8
	"Enable Void Particles" = false
	#If the player is in a skylight level of 8, the fog disappears
	"Void scared of sky" = true

[nether]
	#Disable Nether Fog?
	"Disable Nether Fog" = false
	#Nether Fog Starting Distance
	#Range: 0.1 ~ 1.0
	"Nether Fog Starting Distance" = 0.65

[lava]
	#Disable Lava Fog?
	"Disable Lava Fog" = false
	#Lava Fog Starting Distance
	#Range: 0.1 ~ 100.0
	"Lava Fog Starting Distance" = 30.0

[water]
	#Disable Water Fog?
	"Disable Water Fog" = false
	#Water Fog Density
	#Range: 0.1 ~ 50.0
	"Water Fog Density" = 18.0

