
[Common]
	#Villagers should not take damage when walking in berry bushes.
	disableVillagerDamage = true
	#Wearing boots and leggings prevent players from taking damage in berry bushes
	disableDamageWhenArmored = true
	#Disable berry damage for all entities. If set to true, the other configs do not matter.
	disableBerryDamage = false

