
[graphics]

	[graphics.particle]
		#Should particles render on the delayed buffer? This means they will properly render after clouds do, but could cause issues with mods like sodium.
		buffer_particles = true

