
[Features]
	#Allow interacting with Packages in the player inventory, kinda like a Bundle.
	inventoryInteractions = true
	#Play sounds when players interact with a Package.
	interactionSounds = true
	#If 'true', the item tags `packages:allowlist_package_maker_frame` and `packages:allowlist_package_maker_inner`
	#will be read, and only the items specified in those tags will be allowed to enter the Frame and Core slots of
	#the Package Maker. This is mainly for modpackers to mess with; you should also probably add something to the tooltip
	#lang keys (`packages.package_maker.frame.X`, where X is a one-indexed line number) to describe the behavior you create.
	packageMakerAllowlistMode = false

