
#Specify at least 'use' (right click) or 'punch' (left click), and optionally add
#any combination of 'ctrl', 'alt', or 'sneak' to require some modifier keys.
#Separate multiple items with hyphens. Disable an action entirely by leaving it blank.
[Keys]
	#How do you insert one item into the package?
	insertOne = "use"
	#How do you insert one stack of items into the package?
	insertStack = "sneak-use"
	#How do you insert everything in your inventory that fits into the package?
	insertAll = "ctrl-use"
	#How do you take one item from the package?
	takeOne = "punch"
	#How do you take one stack of items from the package?
	takeStack = "sneak-punch"
	#How do you clear all items from the package?
	takeAll = "ctrl-punch"
	#Older versions of Packages had a "feature" where holding left-click would slowly trickle items out of the Package.
	#This was actually a bug, caused by code intended to differentiatiate between 'starting a left click' and 'continuing
	#a left click' not working correctly; the delay was my band-aid fix.
	#I've since actually fixed it, but I don't know if people had gotten used to the broken behavior :)
	#If you did and want it back, set this to 4.
	punchRepeat = -1

[Model]
	#If 'true', Package and Package Crafter 3d models will be cached in-memory, instead of rebaked from scratch every time.
	#The model bakery is quite fast; this probably helps chunk-bake performance less than it sounds like it would, and consumes memory.
	#However I'm pretty sure it slightly improves the efficiency of item rendering. All's tradeoffs.
	#F3+T will dump the cache.
	cacheMeshes = true
	#For some reason I need this on Forge only, to make the front face of Packages render with the correct color.
	#If you need to reset this to 'false', I'd be interested in hearing what mods you're using.
	swapRedAndBlue = true

