
[General]
	#This value determines the size of a bee. By default 0.25, which means they are 1/4th of their vanilla size. Set to 1.0 to disable the different bee size feature.
	#Range: 0.01 ~ 5.0
	beeSizeModifier = 0.5
	#When enabled, bees die after stinging a player. This takes roughly a few minutes.
	beesDieFromStingingPlayer = false
	#When enabled, bees die after stinging a mob. This takes roughly a few minutes.
	beesDieFromStingingMob = false
	#After a bee stings, it has a chance to leave its stinger inside the entity. It must be pulled out.
	beesLeaveTheirStinger = false
	#After a bee stings a player and its stinger is left behind, send the player a message.
	sendStungPlayerWithStingerAMessage = false
	#The chance the bee's stinger lodges in the stung entity, resulting in death.
	#Range: 0.0 ~ 1.0
	chanceBeeLeavesItsStinger = 0.0
	#The chance the bee's stinger is pulled out by a player after right-clicking shears.
	#Range: 0.0 ~ 1.0
	chanceBeeStingerIsPulledOut = 1.0
	#The time in seconds a stinger that's left in an entity continues to pump poison.
	#Range: 0 ~ 300
	timeInSecondsStingerPumpsPoison = 0
	#The time in a seconds after a bee without its stinger dies.
	#Range: 0 ~ 600
	timeInSecondsBeeWithoutStingerDies = 60
	#In order to make bees a little more common. Whenever a bee naturally spawns, the mod spawns an additional 'extraBeeSpawnsPerBee' bees.
	#Range: 0 ~ 50
	extraBeeSpawnsPerBee = 3
	#How many bees should be able to enter the hive in total. Minecraft's default is 3, but bees are a lot smaller so there should be more space.
	#Range: 0 ~ 50
	beeHiveBeeSpace = 16
	#The smaller (baby) bees can sometimes do something unexpected with their AI and get suffocation damage. Preventing this damage fixes them disappearing.
	preventBeeSuffocationDamage = true

