
#Magic system
[maxLevel]
	#Maximum magician level
	#Range: 1 ~ 50
	max_level = 36

[maxSpellStorage]
	#Maximum number of spells a magician can store
	#Range: 5 ~ 20
	max_spell_storage = 20

[spellCharge1Reload]
	#The time it takes for a first level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_1_reload = 600

[spellCharge2Reload]
	#The time it takes for a second level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_2_reload = 1200

[spellCharge3Reload]
	#The time it takes for a third level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_3_reload = 1800

[spellCharge4Reload]
	#The time it takes for a fourth level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_4_reload = 2400

[spellCharge5Reload]
	#The time it takes for a fifth level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_5_reload = 3600

[spellCharge6Reload]
	#The time it takes for a sixth level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_6_reload = 4800

[spellCharge7Reload]
	#The time it takes for a seventh level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_7_reload = 6000

[spellCharge8Reload]
	#The time it takes for a eighth level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_8_reload = 7200

[spellCharge9Reload]
	#The time it takes for a ninth level spell charge to reload in ticks
	#Range: 20 ~ 28800
	spell_charge_9_reload = 8400

#Debug
[showPacketMessages]
	#Used to display server/client messages in logs for debug purposes, default true, switching to false will hide these messages.
	show_packet_messages = true

[passiveReload]
	#When true, spell charges reload at rates determined below
	passive_reload = true

[sleepReload]
	#When true, spell charges reload when the one sleeps
	sleep_reload = false

