
[ShieldList]
	#
	#List of items to considered as shields, any item with right-click functionality will theoretically work
	#Automatically populated with items that have parrying stats set by active datapacks
	shieldList = ["shieldexp:wooden_shield", "upgradednetherite:phantom_upgraded_netherite_shield", "shieldexp:griefer_shield", "upgradednetherite:echo_upgraded_netherite_shield", "upgradednetherite:water_upgraded_netherite_shield", "shieldexp:iron_shield", "upgradednetherite:poison_upgraded_netherite_shield", "shieldexp:netherite_shield", "upgradednetherite:netherite_shield", "alexsmobs:shield_of_the_deep", "minecraft:shield", "upgradednetherite:corrupt_upgraded_netherite_shield", "shieldexp:golden_shield", "shieldexp:diamond_shield", "shieldexp:paragon_shield", "upgradednetherite:wither_upgraded_netherite_shield", "artifacts:umbrella", "upgradednetherite:ender_upgraded_netherite_shield", "upgradednetherite:gold_upgraded_netherite_shield", "upgradednetherite:fire_upgraded_netherite_shield", "upgradednetherite:feather_upgraded_netherite_shield"]
	#
	#List of items to not consider as shields, even if they have stats set by a datapack
	shieldBlacklist = []

[Modifiers]
	#
	#Disable the cooldown when the player lowers their shield
	noLoweringCooldown = false
	#
	#Disable putting shields on cooldown at all
	noCooldown = false
	#
	#Make all shields have vanilla movement speed
	noSpeedModifier = false
	#
	#Make shields only block partial damage from explosions when not parrying
	harderExplosions = true
	#
	#Double the parry window for a more relaxed experience
	lenientParryMode = true
	#
	#Double the shield stamina for a more relaxed experience
	lenientStaminaMode = false

