
[items]

	[items.trades]
		"Clerics buy thrasher teeth" = true
		"Leatherworkers sell bedrolls" = true

[generation]

	[generation.structures]
		#If Mossy Cobblestone and Stone Bricks are replaced with Kelpy Cobblestone and Stone Bricks in Ocean Ruins
		"Kelpy Ocean Ruins" = true

[mobs]
	#Give Drowneds a swimming animation, like in bedrock edition
	"Drowned swimming animation" = true
	#The max height that deep ocean mobs can spawn at
	#Range: 0 ~ 255
	"Deep ocean mob max height" = 30

	[mobs.spawns]
		"Thrasher spawn weight (cold oceans)" = 10
		"Nautilus spawn weight (warm oceans)" = 50
		"Lionfish spawn weight (coral reefs)" = 15
		"Pike spawn weight (rivers)" = 11
		"Perch spawn weight (swamps)" = 5
		"Pike spawn weight (swamps)" = 5
		"Squid spawn weight (swamps)" = 5

