
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 13408601

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

[create]
	#The default byproduct material to output in Create's crushing.
	byproduct = "minecraft:cobblestone"

[indreb]
	#The default byproduct material to output in Industrial Reborn's crushing.
	byproduct = "indreb:stone_dust"

